[package]
name = "ilc"
version = "0.1.0"
authors = ["shiftysymbol <32494444+shiftysymbol@users.noreply.github.com>"]
edition = "2018"

[dependencies]
termion = "1.5"
structopt = "0.2"
regex = "1"
lazysort = "0.2"
ex = "0.1"

[features]
default = []

# use slow (and slightly incorrect) implementation of line collector
slow_linecollector = []

[dev-dependencies]
criterion = "0.2"

[[bench]]
path = "src/benchmark.rs"
name = "benchmark"
harness = false

[profile.release]
lto = true
opt-level = 'z'  # Optimize for size
codegen-units = 1